version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  app:
    build: .
    container_name: node-app
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://localhost:9200
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
